dist: xenial
sudo: required
language:
  - generic
cache:
  - apt
services:
  - docker

env:
  global:
    - SOURCE_PATH="`pwd`"

install:
  - docker pull ljanyst/ros-udacity

script:
  - docker run -it  -v ${SOURCE_PATH}:/tmp/source ljanyst/ros-udacity /tmp/source/.travis.sh
